server.port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-security
    username: postgres
    password: BEshrek543
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect